apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami-deployment
  namespace: app
  labels:
    app: umami
  annotations:
    keel.sh/policy: force

spec:
  replicas: 3
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/techprober/umami
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami
                  key: DATABASE_URL
            - name: HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: umami
                  key: HASH_SALT

---
apiVersion: v1
kind: Service
metadata:
  name: umami-service
  namespace: app

spec:
  selector:
    app: umami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-ingress
  namespace: app

spec:
  rules:
    - host: umami.cluster.kuin.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umami-service
                port:
                  number: 80
