apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/argo-cd.git
    targetRevision: HEAD
    path: applications/website
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: littlelink
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/argo-cd.git
    targetRevision: HEAD
    path: applications/littlelink
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/argo-cd.git
    targetRevision: HEAD
    path: applications/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/argo-cd.git
    targetRevision: HEAD
    path: applications/umami
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/argo-cd.git
    targetRevision: HEAD
    path: applications/uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
