apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argo-cd

spec:
  description: a collection of homelab applications deployed by kubernetes automation tools
  sourceRepos:
    - "*"
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
