apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: website-pipeline
  namespace: tekton-builds

spec:
  params:
    - name: git-repo-url

    - name: project
      default: website

    - name: container_image
      default: website

  workspaces:
    - name: website
    - name: gitcredentials

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: website
      params:
        - name: url
          value: $(params.git-repo-url)

    - name: build-container-image
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: website
      params:
        - name: dockerfile_path
          value: Dockerfile
        - name: container_image
          value: kunish/$(params.project)
      runAfter:
        - git-clone
