apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: website-trigger-binding
  namespace: tekton-builds

spec:
  params:
    - name: git-revision
      value: $(body.pull_request.head.sha)
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-api-url
      value: $(body.repository.url)
    - name: git-branch
      value: $(body.pull_request.head.ref)
    - name: namespace
      value: tekton-builds
    - name: content-type
      value: $(header.Content-Type)
