apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: app
  labels:
    app: website
  annotations:
    keel.sh/trigger: poll
    keel.sh/policy: force
    keel.sh/pollSchedule: "@every 10s"

spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: kunish/website:main
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: app

spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  namespace: app

spec:
  rules:
    - host: website.cluster.kuin.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website-service
                port:
                  number: 80
