kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma-deployment
  namespace: app
  labels:
    app: uptime-kuma
  annotations:
    keel.sh/policy: force

spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uptime-kuma-vol
              mountPath: /app/data
      volumes:
        - name: uptime-kuma-vol
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: app

spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: app

spec:
  rules:
    - host: uptime-kuma.cluster.kuin.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-service
                port:
                  number: 80
