apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: production

nameSuffix: -production

resources:
  - ../base

images:
  - name: ghcr.io/kunish/website
    newTag: 1.0.0
