apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: staging

nameSuffix: -staging

resources:
  - ../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: website-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: website-staging.cluster.kuin.sh

images:
  - name: ghcr.io/kunish/website
    newTag: staging
